#config: None
max_frames: 200
eval_frames: 500
batch_size: 256
max_seg_per_spk: 200
nDataLoaderThread: 5
test_interval: 1
max_epoch: 300
trainfunc: aamsoftmax
alpha: 1.0
optimizer: adam
scheduler: ReduceLROnPlateau
lr: 0.005
lr_decay: 0.5
weight_decay: 5e-05
margin: 0.1
scale: 30
nPerSpeaker: 1
nClasses: 1211
# initial_model: 
save_path: /home/lcf/speaker/Discriminative_Speaker_Embedding_Extractor/exps/NeXtVLAD_AAMS_m0.1_nC10_nG8
train_list: /home/data_ssd/lcf/API-Net_VoxExp/data/vox1_train/feats.scp
test_list: /home/data_ssd/lcf/API-Net_VoxExp/data/vox1_test/trials_ark
n_mels: 40
log_input: False
model: ResNetSE34L
encoder_type: NeXtVLAD
MultiStageAgg: False
MSA_type: 1234
num_clusters: "10"
groups: "8"
expansion: "2"
vlad_drop: 0
nOut: 512
GPUid: 2