#config: None
max_frames: 200
eval_frames: 500
batch_size: 128
max_seg_per_spk: 200
nDataLoaderThread: 5
test_interval: 1
max_epoch: 300
trainfunc: amsoftmaxproto
alpha: 1.0
optimizer: adam
scheduler: ReduceLROnPlateau
lr: 0.005
lr_decay: 0.5
weight_decay: 5e-05
margin: 0.1
scale: 30
nPerSpeaker: 2
nClasses: 1211
# initial_model: 
save_path: /home/lcf/speaker/Discriminative_Speaker_Embedding_Extractor/exps/MSA-NeXtVLAD_AMS_APL_m0.1_S234-nC3x10_nG248
train_list: /home/data_ssd/lcf/API-Net_VoxExp/data/vox1_train/feats.scp
test_list: /home/data_ssd/lcf/API-Net_VoxExp/data/vox1_test/trials_ark
n_mels: 40
log_input: False
model: ResNetSE34L
encoder_type: NeXtVLAD
MultiStageAgg: True
MSA_type: 234
num_clusters: "10_10_10"
groups: "2_4_8"
expansion: "2_2_2"
vlad_drop: 0
nOut: 512
GPUid: 1